### ISSUE TITLE
can't disable minibuffer system-load info

### ISSUE THREAD

**Issue by No42-Baili** [gujiaxi/.emacs.d#1]
hey bro, i find there is a system-load info in minibuffer and i can't find somewhere turn it off.
can you tell my how to turn off this?
![minibuffer-sysload](https://user-images.githubusercontent.com/14740069/66992818-13238d80-f0fd-11e9-81f1-436bb8c8d177.jpg)

**Comment by gujiaxi** [comment]
Hi, the information is generated by [symon](https://github.com/zk-phi/symon), the corresponding part in `.init.el` is located in [Line 653](https://github.com/gujiaxi/.emacs.d/blob/2c8e1fd567a089a7d44c3fd653273b902d92508a/init.el#L653). You can turn it off by add `:disabled` as follows:

```
;; symon
(use-package symon
  :disabled
  :custom (symon-delay 33)
  :config (symon-mode))
```

or you can just delete the symon-related lines.

**Comment by No42-Baili** [comment]
thx, that work
